name: CI
on:
  push:
    branches: ["*"]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: deno test --allow-read --allow-write

      ## The --allow-dirty is needed here because in CI the deno.lock file may be modified
      - name: JSR check
        run: deno publish --dry-run --allow-dirty
